language: python
install: pip install -r requirements-test.txt
python:
- '2.7'
script: PYTHONPATH='.' py.test --cov=statiki --cov=github_utils --cov=travis_utils --cov-report=term-missing tests/
env:
  global:
    secure: XxLhvogFDQ/TkUWMcj6J2W6yL0L0Zj2Pisq2+xwInG78GrizXQJkuXgvtyams8GI/KXew/Y5YbGkiR+395V8YTL7gF5SFtvb/YUBXCl00LsxBJe9ZYZKboN5wPWERgaunypTvHVAObBHS7Zmmu21GcOqCkZMIUsqPQNLXZTj7IQ=
after_success:
  - coveralls
